services:

  #api development build
  payload:
    build:
      target: payload-dev
    container_name: payload.dev
    depends_on:
      - db
    environment:
      ZITADEL_API_JWT_FILE: /run/secrets/zitadel_api_jwt
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    profiles:
      - development
    secrets:
      - zitadel_api_jwt
    restart: unless-stopped

  #api production test build
  payload-prod:
    build:
      target: payload-prod
    container_name: payload.prod
    depends_on:
      - db
    environment:
      ZITADEL_API_JWT_FILE: /run/secrets/zitadel_api_jwt
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    profiles:
      - production
    secrets:
      - zitadel_api_jwt
    restart: unless-stopped

  #db development build
  db:
    build:
      target: db
    container_name: db.dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: db_data
        target: /data/db
      - type: volume
        source: db_config
        target: /data/configdb

networks:
  default:
    name: workspace-dev

secrets:
  zitadel_api_jwt:
    environment: ZITADEL_API_JWT

volumes:
  db_data:
    name: workspace-vol-db-data
  db_config:
    name: workspace-vol-db-config