services:

  #api development build
  payload:
    build:
      target: payload-dev
    container_name: payload.dev
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - db
    profiles:
      - development
    restart: unless-stopped

  #api production test build
  payload-prod:
    build:
      target: payload-prod
    container_name: payload.prod
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - db
    profiles:
      - production
    restart: unless-stopped

  #db development build
  db:
    build:
      target: db
    container_name: db.dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /data/db
      - type: volume
        source: db-config
        target: /data/configdb

networks:
  default:
    name: workspace-dev

volumes:
  db-data:
    name: workspace-vol-db-data
  db-config:
    name: workspace-vol-db-config