allowBuilds:
  '@swc/core': true
  esbuild: false
  sharp: false

catalogs:
  framework:
    next: ^16.2.10
    react: ^19.2.7
    react-dom: ^19.2.7
    '@types/react': ^19.2.17
    '@types/react-dom': ^19.2.3
  payload:
    payload: ^3.86.0
    '@payloadcms/db-mongodb': ^3.86.0
    '@payloadcms/next': ^3.86.0
    '@payloadcms/richtext-lexical': ^3.86.0
    '@payloadcms/translations': ^3.86.0
    '@payloadcms/ui': ^3.86.0
  libs:
    jose: ^6.2.3
  environment:
    '@types/node': ^26.1.1
    typescript: ^7.0.2
  utils:
    '@swc/cli': ^0.8.1
    '@swc/core': ^1.15.43
    rimraf: ^6.1.3

minimumReleaseAge: 60

packages:
  - dev
