gen-types:
	export ZITADEL_URL="test" && export ZITADEL_CLIENT_ID="test" && export PAYLOAD_CONFIG_PATH=src/config/payload.config.ts && pnpm run gen:types

gen-imap:
	export ZITADEL_URL="test" && export ZITADEL_CLIENT_ID="test" && export PAYLOAD_CONFIG_PATH=src/config/payload.config.ts && pnpm run gen:imap