name: Publish package to GitHub Packages
on:
  release:
    branches: 'main'
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.5
      - run: deno publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}